name: Tests on commit
on: [push]
jobs:
  x86_64-apple-darwinXX:
    runs-on: [macOS, Intel]
    steps:
      - uses: actions/checkout@v5
      - run: make test
  arm64-apple-darwinXX:
    runs-on: [macOS, arm64]
    steps:
      - uses: actions/checkout@v5
      - run: make test
  x86_64-linux-gnu:
    runs-on: [linux, x64]
    steps:
      - uses: actions/checkout@v5
      - run: make test
  arm64-linux-gnu:
    runs-on: [linux, arm64]
    steps:
      - uses: actions/checkout@v5
      - run: make test
